### ISSUE TITLE
Create public room for the repository on gitter.im

### ISSUE THREAD

**Issue by scout119** [NETMF/netmf-interpreter#109]
I really like the quick feedback loop that gitter provides. See the dotnet/roslyn room:
https://gitter.im/dotnet/roslyn

Would be nice if you guys create public room for NETMF/netmf-interpreter.

Thank you,
Valentin

**Comment by smaillet-ms** [comment]
Out of curiosity, what do you see as the benefits of using that over using the existing GitHub system. I looked at the link provided and couldn't really see any value in gitter vs. GitHub. (Not that I think GitHub is the greatest thing since sliced bread, at this point I just don't see gitter is really offering anything better)

**Comment by scout119** [comment]
Gitter is an addition to GitHub. It is the GitHub's chat system with major mobile and desktop clients. Just very convenient to use. Doesn't cost anything to enable it. A good place for quick Q@A or any other live discussions. Totally optional :)

Thanks,
Valentin

**Comment by zezba9000** [comment]
@smaillet-ms Its a place to chat with like minded people and ask questions.  GitHub discussions are good but its not the same thing.  With gitter we can ask question or talk about stuff we work on that may not be good for this section.

**Comment by smaillet-ms** [comment]
@zezba9000 But the conversation still ends up here in GitHub anyway AFAIK, so that's why I'm unclear on the value.

**Comment by zezba9000** [comment]
Because I can have coreclr open, Roslyn open ect all in one window.  You can see who is online, who read your post, who is typing (I think).  You can have lots of channels and topics open and you don't need to get emailed everytime someone messages you.  It works like IRC but keeps track of text in case of a connection break or you put your computer to sleep.  GitHub issues is like a forum not really very interactive for quick chats.  Maybe an IRC channel would be better but Gitter is just being used by all the other .NET projs is why it might be nice.

If the conversation goes on Github where (didn't know this [chat info isn't kept around forever I wouldn't think)?   Also it probably requires you to refresh your page all the time to get updates.
