### ISSUE TITLE
Branch Support-GCC/STM32F4 Discovery: wrong native checksum for Windows.Devices assembly

### ISSUE THREAD

**Issue by maiorfi** [NETMF/netmf-interpreter#194]
At boot:

 Loading start at 8050f0c, end 80644dc

  ...
   
__Invalid native checksum: Windows.Devices 0xF4E46B74!=0xF71D0B80__

...
Error: 96000000

Waiting for debug commands...

**Comment by cw2** [comment]
As a quick workaround, update the value in `g_CLR_AssemblyNative_Windows_Devices` structure at the end of `CLR\Libraries\Windows_Devices\windows_devices_native.cpp`, or comment out all lines that contain "Windows_Devices" in TinyCLR.proj in the Discovery solution (to exclude the assembly from firmware image).

I guess there could be a problem in one of the recent merges - to be investigated...

**Comment by maiorfi** [comment]
Indeed I did it and solved, thanks. Nevertheless it's likely to be a real bug due to a mismatch between interop native and managed parts, isn't it?

**Comment by smaillet-ms** [comment]
There was a bug on that and fixed in dev. The GCC-Support branch hasn't been merged with the current dev in a while. Given that there are now a few people successfully making progress on GCC it may be worth just rolling it up into the dev branch and avoiding further discrepancies. It was originally set up so that multiple people could get going while potentially needing to modify core files to compile properly with GCC. Now that we are past that stage there doesn't seem to be much of a reason to keep this in a separate branch anymore. @maiorfim, @cw2  Thoughts?

**Comment by cw2** [comment]
:+1: :ok_hand: :satisfied:

**Comment by maiorfi** [comment]
It would be great!

**Comment by piwi1263** [comment]
You've got my big thumbs up as well !!! :+1: :+1:

2015-06-24 7:26 GMT+02:00 maiorfi <notifications@github.com>:

**Comment by smaillet-ms** [comment]
ok, sounds like consensus to me. :tongue: 
It might be a couple days before I can get to doing a merge, hopefully that will go easily as we did a fairly big rebase/merge not too long ago and I don' think there are any areas where I'll be stuck in manual merge hell...

**Comment by smaillet-ms** [comment]
Well that was easier than I thought! Fortunately the previous large rebase/merge worked out all the kinks and only a couple small conflicts existed. So it all went in. Woohoo! :joy:

**Comment by cw2** [comment]
:clap:
