### ISSUE TITLE
STDIO is not initialized in TinyBooter

### ISSUE THREAD

**Issue by cw2** [NETMF/netmf-interpreter#218]
_Split from #217_

I've found another problem related to ITM - it does not work in Tinybooter. Respectively, it now only works when all four ports (DEBUG_TEXT_PORT, STDIO, DEBUGGER_PORT and MESSAGING_PORT) are set to the same value and it has to be either USBx or COMx.

In Tinybooter (Initialization\tinyhal.cpp) the communication initialization function CPU_InitializeCommunication() is never called (conditional compilation), so the initialization of STDIO depends on its type - if it is set to ITM0, it never happens, if it is set to USBx or COMx, it is initialized when either debugger or messaging does it, whichever is called first.

**Comment by smaillet-ms** [comment]
As discussed the issue is technically unrelated to ITM. It has to do with how the startup and transport initialization and startup work in tinybooter vs. the other projects. It's not clear why that was done differently and if there is any size/perf benefits to short cutting that over keeping things consistent and standard. My current recommendation on this is to modify the tinybooter start up so it is consistent and calls CPU_InitializeCommunication().

**Comment by smaillet-ms** [comment]
I'll fix this at the same time as I fix the STM32 UART code. (in progress now)
