### ISSUE TITLE
Processor Selection - ARM9

### ISSUE THREAD

**Issue by rrideAMT** [NETMF/netmf-interpreter#379]
With NET MF V4.4, to use the networking stack with the CMSIS implementation, does this require an ARM Cortex-M processor?
I ported NET MF to iMXS and iMXL hardware previously and last updated to NET MF V4.1.  Starting a project to update hardware/firmware on these products.  Was hoping to stay with NET MF and leaning towards an iMX28 processor, an ARM9 core, to take advantage of the NXP/freescale longevity program and my knowledge of the NET MF port of the iMXS and iMXL processors.
I have RVDS 4.1, is it possible use this tool chain with NET MF V4.4?
I would like to take advantage of the NET MF V4.4 networking improvements or find reliable work around(s) in NET MF V4.1.  I am running an http server on my product.
Thanks.

**Comment by smaillet-ms** [comment]
There's not much that ties NETMF to the CMSIS-RTX implementation as long as there is CMSIS-RTOS API compatibility. Thus you could use the Freescale MQX with some additional header file and code wrappers to make it CMSIS-RTOS API compliant (If Freescale hasn't already done that). Otherwise you'd need to do a bit more work in the sys_arch layer of the LWIP stack and the system startup code to work on whatever OS you want. (In early development of this new stack we had a version running on Windows using WinPCap as the Ethernet driver so alternate OS support is certainly plausible)
